# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lyra's blog
email: s.lyra@ya.ru
description: > 
  This is my simple blog.
  It's about electrotechnics, programming, art, ponies, opensource, linux and etc...
  Progrmming langs: C# Python C++ Bash
  Micricontroller types: stm32 avr arduino
  My mail: s.lyra@ya.ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
github_username:  SL-RU

excerpt_separator: "<!-- more -->"


# Build settings
markdown: kramdown

